name = "daxiaoren-api"
main = "src/worker.js"
compatibility_date = "2026-02-01"

[vars]
# API Key 将在 Cloudflare Dashboard 中设置
# API_KEY = "d946d990667549baba87595dadb30b42.5r3iUUtIbhPQ5kwA"
API_KEY = "d946d990667549baba87595dadb30b42.5r3iUUtIbhPQ5kwA"

